name: "ZAP API Scan CI workflow"


on:
  push:
    branches: [ test ]


jobs:

# https://github.com/marketplace/actions/owasp-zap-api-scan
 ubuntu-latest-zap-api-basic-job:
    name: "basic - the OWASP ZAP API scan to perform Dynamic Application Security Testing (DAST) ubuntu latest"
    runs-on: ubuntu-latest
    steps:
      - name: "ZAP API Scan"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
        # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'https://www.zaproxy.org/'     
      - name: "ZAP API Scan"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
        # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'http://testphp.vulnweb.com'            

# https://github.com/marketplace/actions/owasp-zap-api-scan
 ubuntu-latest-zap-full-advanced-job:
    name: "advanced - the OWASP ZAP API scan to perform Dynamic Application Security Testing (DAST) ubuntu latest"
    runs-on: ubuntu-latest
    steps:
      - name: "ZAP API Scan"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          format: openapi
          target: 'https://www.zaproxy.org/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

  # ubuntu-latest-job:
  #   name: "kali-tools-database ubuntu latest"
  #   runs-on: ubuntu-latest
  #   env:
  #     distribution: "kalilinux" #https://hub.docker.com/r/kalilinux/kali-rolling
  #     version: "latest"
  #     name: "kali/kali-tools-database"
  #     dockerfilename: "Dockerfile.kalilinux.kali-tools-database"
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: |
  #       hostnamectl status
  #       lsb_release -a
  #       lsb_release -d
  #       cat /etc/lsb-release
  #       cat /etc/issue
  #       cat /etc/os-release
  #       sudo apt-get install -y neofetch && neofetch   
  #   - name: "docker build kali linux"
  #     run: |
  #       # destroyed afterwards (use --rm )
  #       # all subsequent Dockerfile commands generate new images and the cache is not used
  #       sudo docker build --no-cache --rm  -t ${name}:${version} . --file dockerfiles/${dockerfilename} 
  #       docker image ls
  #       docker image history ${name}:${version}
  #       docker system df -v               
  #       docker image inspect ${name}:${version}  
  #       docker container ls -a
                  

  # ubuntu-2004-job:
  #   name: "kali-tools-database ubuntu  20.04"
  #   runs-on: ubuntu-20.04
  #   env:
  #     distribution: "kalilinux" #https://hub.docker.com/r/kalilinux/kali-rolling
  #     version: "latest"
  #     name: "kali/kali-tools-database"
  #     dockerfilename: "Dockerfile.kalilinux.kali-tools-database"    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: |
  #       hostnamectl status
  #       lsb_release -a
  #       lsb_release -d
  #       cat /etc/lsb-release
  #       cat /etc/issue
  #       cat /etc/os-release
  #       sudo apt-get install -y neofetch && neofetch   
  #   - name: "docker build kali linux"
  #     run: |
  #       # destroyed afterwards (use --rm )
  #       # all subsequent Dockerfile commands generate new images and the cache is not used
  #       sudo docker build --no-cache --rm  -t ${name}:${version} . --file dockerfiles/${dockerfilename} 
  #       docker image ls
  #       docker image history ${name}:${version}
  #       docker system df -v               
  #       docker image inspect ${name}:${version}  
  #       docker container ls -a
        


  # ubuntu-1804-job:
  #   name: "kali-tools-database ubuntu-18.04"
  #   runs-on: ubuntu-18.04
  #   env:
  #     distribution: "kalilinux" #https://hub.docker.com/r/kalilinux/kali-rolling
  #     version: "latest"
  #     name: "kali/kali-tools-database"
  #     dockerfilename: "Dockerfile.kalilinux.kali-tools-database"    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: |
  #       hostnamectl status
  #       lsb_release -a
  #       lsb_release -d
  #       cat /etc/lsb-release
  #       cat /etc/issue
  #       cat /etc/os-release
  #       sudo apt-get install -y neofetch && neofetch    
  #   - name: "docker build kali linux"
  #     run: |
  #       # destroyed afterwards (use --rm )
  #       # all subsequent Dockerfile commands generate new images and the cache is not used
  #       sudo docker build --no-cache --rm  -t ${name}:${version} . --file dockerfiles/${dockerfilename} 
  #       docker image ls
  #       docker image history ${name}:${version}
  #       docker system df -v               
  #       docker image inspect ${name}:${version}  
  #       docker container ls -a




