name: "ZAP Full Scan CI workflow"


on:
  push:
    branches: [ test ]

jobs:

# https://github.com/marketplace/actions/owasp-zap-full-scan
 ubuntu-latest-zap-full-basic-job:
    name: "basic -The OWASP ZAP Full Scan to perform Dynamic Application Security Testing (DAST) ubuntu latest"
    runs-on: ubuntu-latest
    steps:
      - name: "ZAP Full Scan"
        uses: zaproxy/action-full-scan@v0.3.0
        with:
        # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'http://testphp.vulnweb.com'    

# https://github.com/marketplace/actions/owasp-zap-full-scan
 ubuntu-latest-zap-full-advanced-job:
    name: "advanced - The OWASP ZAP Full Scan to perform Dynamic Application Security Testing (DAST) ubuntu latest"
    runs-on: ubuntu-latest
    steps:
      - name: "ZAP Full Scan http://testphp.vulnweb.com"
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'http://testphp.vulnweb.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      - name: "ZAP Full Scan http://demo.testfire.net/"
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'http://demo.testfire.net/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'          
      - name: "ZAP Full Scan https://dvwa.co.uk/"
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'https://dvwa.co.uk/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      - name: "ZAP Full Scan https://ctflearn.com/"
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'https://ctflearn.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'          
      - name: "ZAP Full Scan https://ctflearn.com/"
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'https://ctflearn.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a' 
      - name: "ZAP Full Scan https://www.gameofhacks.com/"
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'https://www.gameofhacks.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'           
      - name: "ZAP Full Scan https://public-firing-range.appspot.com/"
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'https://public-firing-range.appspot.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a
      - name: "ZAP Full Scan http://google-gruyere.appspot.com/"
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'http://google-gruyere.appspot.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a          

  # ubuntu-latest-job:
  #   name: "kali-tools-database ubuntu latest"
  #   runs-on: ubuntu-latest
  #   env:
  #     distribution: "kalilinux" #https://hub.docker.com/r/kalilinux/kali-rolling
  #     version: "latest"
  #     name: "kali/kali-tools-database"
  #     dockerfilename: "Dockerfile.kalilinux.kali-tools-database"
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: |
  #       hostnamectl status
  #       lsb_release -a
  #       lsb_release -d
  #       cat /etc/lsb-release
  #       cat /etc/issue
  #       cat /etc/os-release
  #       sudo apt-get install -y neofetch && neofetch   
  #   - name: "docker build kali linux"
  #     run: |
  #       # destroyed afterwards (use --rm )
  #       # all subsequent Dockerfile commands generate new images and the cache is not used
  #       sudo docker build --no-cache --rm  -t ${name}:${version} . --file dockerfiles/${dockerfilename} 
  #       docker image ls
  #       docker image history ${name}:${version}
  #       docker system df -v               
  #       docker image inspect ${name}:${version}  
  #       docker container ls -a
                  

  # ubuntu-2004-job:
  #   name: "kali-tools-database ubuntu  20.04"
  #   runs-on: ubuntu-20.04
  #   env:
  #     distribution: "kalilinux" #https://hub.docker.com/r/kalilinux/kali-rolling
  #     version: "latest"
  #     name: "kali/kali-tools-database"
  #     dockerfilename: "Dockerfile.kalilinux.kali-tools-database"    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: |
  #       hostnamectl status
  #       lsb_release -a
  #       lsb_release -d
  #       cat /etc/lsb-release
  #       cat /etc/issue
  #       cat /etc/os-release
  #       sudo apt-get install -y neofetch && neofetch   
  #   - name: "docker build kali linux"
  #     run: |
  #       # destroyed afterwards (use --rm )
  #       # all subsequent Dockerfile commands generate new images and the cache is not used
  #       sudo docker build --no-cache --rm  -t ${name}:${version} . --file dockerfiles/${dockerfilename} 
  #       docker image ls
  #       docker image history ${name}:${version}
  #       docker system df -v               
  #       docker image inspect ${name}:${version}  
  #       docker container ls -a
        


  # ubuntu-1804-job:
  #   name: "kali-tools-database ubuntu-18.04"
  #   runs-on: ubuntu-18.04
  #   env:
  #     distribution: "kalilinux" #https://hub.docker.com/r/kalilinux/kali-rolling
  #     version: "latest"
  #     name: "kali/kali-tools-database"
  #     dockerfilename: "Dockerfile.kalilinux.kali-tools-database"    
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: |
  #       hostnamectl status
  #       lsb_release -a
  #       lsb_release -d
  #       cat /etc/lsb-release
  #       cat /etc/issue
  #       cat /etc/os-release
  #       sudo apt-get install -y neofetch && neofetch    
  #   - name: "docker build kali linux"
  #     run: |
  #       # destroyed afterwards (use --rm )
  #       # all subsequent Dockerfile commands generate new images and the cache is not used
  #       sudo docker build --no-cache --rm  -t ${name}:${version} . --file dockerfiles/${dockerfilename} 
  #       docker image ls
  #       docker image history ${name}:${version}
  #       docker system df -v               
  #       docker image inspect ${name}:${version}  
  #       docker container ls -a




